export default {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  UPDATE_USER_SETTING: 'UPDATE_USER_SETTING',
  SIGNOUT: 'SIGNOUT',

  LOAD_GROUPS: 'LOAD_GROUPS',
  LOAD_MEETINGS: 'LOAD_MEETINGS',
  LOAD_FEW_MEETINGS: 'LOAD_FEW_MEETINGS',
  LOAD_GROUP_NOTICES: 'LOAD_GROUP_NOTICES',
  LOAD_FEW_GROUP_NOTICES: 'LOAD_FEW_GROUP_NOTICES',
  LOAD_MEETING_NOTICES: 'LOAD_MEETING_NOTICES',
  LOAD_POLICIES: 'LOAD_POLICIES',
}
