export default {
  LOGOUT: 'LOGOUT',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',

  UPDATE_USER_SETTING: 'UPDATE_USER_SETTING',

  LOAD_GROUPS: 'LOAD_GROUPS',
  JOIN_GROUP: 'JOIN_GROUP',
  DELETE_GROUP: 'DELETE_GROUP',
  
  LOAD_MEETINGS: 'LOAD_MEETINGS',
  LOAD_GROUP_NOTICES: 'LOAD_GROUP_NOTICES',
  LOAD_MEETING_NOTICES: 'LOAD_MEETING_NOTICES',
  LOAD_POLICIES: 'LOAD_POLICIES',
  LOAD_MEETING_FINES: 'LOAD_MEETING_FINES',
}
